appName: REPOSITORY_NAME
namespace: default

release:
  deploy: false
  apiTier: Tier1
  language: nodejs
  squad: default
  component: api
  netDLL: Example.API.dll
  apiContainerPort: 80
  envvars:
    KEY: value
image:
  repository: acrurl.azurecr.io/appname
  tag: latest
# valores custom para el chart de api-template
healthchecks:
  enabled: true

ingress:
  enabled: false

nodeSelector: {}
#  key: value

service:
  apiServicePort: 80
  serviceType: ClusterIP

redis:
  enabled: false
  image: redis:7.0.5-alpine3.16
  port: 6379
  tier: redis-low-resource-usage

autoscaling:
  averageCPU: 80
  averageMEM: 80

deployment:
  PullPolicy: Always
  limitsCPU: 100m
  limitsMEM: 128Mi
  requestsCPU: 100m
  requestsMEM: 128Mi
