{{ if .Values.release.deploy }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: service-port
      protocol: TCP
      port: {{ .Values.service.apiServicePort }}
      targetPort: {{ .Values.release.apiContainerPort }}

{{ end }}